FROM centos:7.3.1611

RUN yum install -y make gcc gcc-c++ openssl-devel libxml2-devel boost-devel libcgroup-devel wget libcgroup-tools ruby-devel which rpm-build libtool check-devel openssh-clients hwloc-devel pam-devel && \
    gem install fpm
